### ISSUE TITLE
Papers to publish

### ISSUE THREAD

**Issue by adebali** [biowonks/projects#4]
Along with MiST, we should publish Biowonks/projects repository in a specialized journal such as _Source Code for Biology and Medicine_. 

The point is to write about the technical details of the repository as well as our vision.

Subjects to cover: 
- Standardized environment with Docker.
- Mono repo
- Unit tests and coverage
- Documentation
- Open source
- Continous integration
- Open to host any project as long as "Biowonks" rules are applied (unit tests, docker etc).

**Comment by daviortega** [comment]
Hi Ogun,

I think this is a good idea, but let's discuss a bit in slack. For instance, we need to know who will pay for those. I have a similar idea.

**Comment by daviortega** [comment]
@adebali @ToshkaDev and @lukeulrich, do you guys have an interest in doing this? Otherwise, we can close this issue with a `wontfix` tag

**Comment by adebali** [comment]
Agreed.
