### ISSUE TITLE
Eukaryote support

### ISSUE THREAD

**Issue by adebali** [biowonks/projects#5]
In the mist-pipeline, we can run eukaryotic genomes as well. 

Things to consider:
- One gene --> multiple protein isoforms (The biggest problem)
- Take care of introns
- Gene clustering algorithm would be different. (Maybe even not needed)
- Prokaryotic Signal Transduction profiles will not be computed

**Comment by daviortega** [comment]
I **strongly** support this idea!

**Comment by daviortega** [comment]
@adebali what would it take to include Eukaryotes on MiST? Do you have the bandwidth to tackle the Isoform problem?

**Comment by adebali** [comment]
Thanks for raising this issue up. As we deal with eukaryotes we have some ideas on how to address these problems. As of now, however, we don't have the technical capacity to implement tour ideas in the current framework (node.js, database etc.). 

Uniprot might be a better choice for eukaryotes. Changing the primary data source (NCBI) might not be a good idea though.

So it is likely going to be a separate project. Therefore, I think we can close this issue here.

**Comment by daviortega** [comment]
Let's close it for now, but I think it would be stronger to start making the case for Eukaryotic support (and include Uniprot too) for MiST4.
