### ISSUE TITLE
new standard for header of exported fasta format

### ISSUE THREAD

**Issue by daviortega** [biowonks/projects#61]
I am being selfish here, but I thought about this problem for a while and I combined several things I heard from folks like Kristin Wuichet and other people in the Zhulin lab in the past.

When we look at a header it is important to know which organism the sequence is from, and to not provide redundant information.

So, with this new standard from MiST I propose this:

`Xx_yyy|genomeVersion-locus|description`

where `Xx` is the first two letters of the genus and `yyy` the first three letters of the species.

For example:

|organism| Xx_yyy|
|---|---|
|_Vibrio cholerae_| Vi_cho |
|_Pseudomonas aeruginosa_| Ps_aer |
|_Escherichia coli_| Es_col |

It would go from this:  
`WP_059398544.1|AMK58_RS01960|GCF_001315015.1-AMK58_RS01960| hypothetical protein [Azospirillum brasilense strain Sp7]`

to this:  
`Az_bra|GCF_001315015.1-AMK58_RS01960| hypothetical protein`

obviously, the field in position `1`, if this header is split by `|`, would be the MiST gene identifier used in the route `/genes`

What do you guys think?

**Comment by ToshkaDev** [comment]
What about giving a user these two options?

**Comment by daviortega** [comment]
> What about giving a user these two options?

That was my first thought but increases the complexity...

**Comment by daviortega** [comment]
I am going to close this for now... I tried to work with standards in real life and it turned out to be a nightmare.

I don't think this was implemented, so let's fold it.
