### ISSUE TITLE
"504 Gateway Time-out" or "502 Bad Gateway"  when connecting to API for some pages and not others

### ISSUE THREAD

**Issue by megarber** [biowonks/projects#92]
conn.request("GET", "/v1/genomes/GCF_000007565.2/signal-genes?page=**1**&per_page=100")
returns 504 gateway time-out or 502 bad gateway error

conn.request("GET", "/v1/genomes/GCF_000007565.2/signal-genes?page=**2**&per_page=100")
does not return an error

**Comment by lukeulrich** [comment]
Hi @megarber deployed a fix last night. Please lmk if you are still seeing this problem

**Comment by megarber** [comment]
Yes, it seems to be working now! Thanks so much for the quick fix!

best,
Megan
