### ISSUE TITLE
Total count in 'Major modes' table does not give results

### ISSUE THREAD

**Issue by ToshkaDev** [biowonks/projects#95]
![Major modes_Table](https://user-images.githubusercontent.com/16031590/111205173-522d6b00-859d-11eb-99bc-0b2651941fff.png)

When clicking on total count values (shown on the picture) no results can be retrieved.

**Comment by lukeulrich** [comment]
Increased the shared memory on the postgres database container to 1GB. Working in my tests.

https://stackoverflow.com/a/57396112

**Comment by ToshkaDev** [comment]
Thank you. It is fixed now.
